### ISSUE TITLE
Select audio streams

### ISSUE THREAD

**Issue by orfisat** [i4tv/gstreamill#101]
Hello select audio streams not work:

"bins" : [
            "udpsrc ! queue ! mpegtsdemux name=demuxer",
            "demuxer.video_0201 ! queue ! h264dec ! queue ! appsink name = video",
            "demuxer.audio_026d ! queue ! mad ! queue ! appsink name = audio_eng",
            "demuxer.audio_0271 ! queue ! mad ! queue ! appsink name = audio_tha",
            "demuxer.private_044f ! queue ! appsink name = subtitle_eng"
        ]

"bins" : [
                    "appsrc name=video ! queue ! videoscale ! queue ! x264enc ! queue ! muxer.",
                    "appsrc name=audio_eng is-live=TRUE ! queue ! audioconvert ! queue ! faac name=faac1 outputformat=1 ! queue ! muxer.",
                    "appsrc name=audio_tha is-live=TRUE ! queue ! audioconvert ! queue ! faac name=faac2 outputformat=1 ! queue ! muxer.",
                    "appsrc name=subtitle_eng ! queue ! muxer.",
                    "mpegtsmux name=muxer ! queue ! appsink sync=FALSE"
            ]

My be version 0.9.1 have bugs ?
Thanks!

**Comment by zhangping** [comment]
@orfisat can u record the stream and send to me?

**Comment by orfisat** [comment]
Hello please send email for sending file (18 Mb).

Best rgerads!

Orfi

**Comment by orfisat** [comment]
Hello send file in zip format. Thanks!

[test.ts.zip](https://github.com/i4tv/gstreamill/files/1298373/test.ts.zip)

**Comment by zhangping** [comment]
download failure @orfisat ，can u give a http download at your own server

**Comment by orfisat** [comment]
Hello, http://128.140.176.226:59888/trailers/test.ts

Thanks!

**Comment by zhangping** [comment]
a problem exist for multi audio track, I will resolve it

**Comment by orfisat** [comment]
Ok thanks! Very nice project!

**Comment by zhangping** [comment]
@orfisat use examples/multiaudio.job and lastest code test audio select, pls

**Comment by orfisat** [comment]
Hello, all work fine!!! Many Thanks!

p.s. Version 0.9.1 work with Overlay DVB subtitles?

**Comment by zhangping** [comment]
@orfisat Does not work with overlay DVB subtitles

**Comment by orfisat** [comment]
Ok thanks!
