### ISSUE TITLE
添加高清转码任务后服务频繁重启

### ISSUE THREAD

**Issue by yungang** [i4tv/gstreamill#49]
添加高清转码任务，不管有没有勾选DVR选项，服务后台运行后，频繁重启，vlc无法播放
但是前台调试模式运行，只打印警告信息，vlc可播放

**Comment by zhangping** [comment]
@yungang 你先跟踪一下吧，先从多码率 + dvr入手，然后再考虑高清的情况。

**Comment by zhangping** [comment]
job的问题造成的
