### ISSUE TITLE
the format of response is inconsistent : getnetworkinterfaces

### ISSUE THREAD

**Issue by yungang** [i4tv/gstreamill#52]
[
    {
        "name": "\"em1\"",
        "address": "\"10.10.5.2\"",
        "netmask": "\"24\"",
        "gateway": "\"10.10.5.1\""
    },
    {
        "name": "em4",
        "address": "192.169.0.22"
    },
    {
        "name": "em3"
    },
    {
        "name": "em2"
    }
]

**Comment by zhangping** [comment]
藏运港有空弄一下吗？

**Comment by yungang** [comment]
正在搞
