### ISSUE TITLE
 ERROR                default gstudpnetutils.c:92:gst_udp_parse_uri: error parsing uri 237.123.43.3:6120: no protocol

### ISSUE THREAD

**Issue by g522342435** [i4tv/gstreamill#54]
在前台运行job时，提示错误，但是在运行过程中跳过错误打印log如下：
(gstreamill:201831): GStreamer-CRITICAL **: gst_uri_get_protocol: assertion 'gst_uri_is_valid (uri)' failed
0:00:00.023121914 201831      0x1ee4d90 ERROR                default gstudpnetutils.c:92:gst_udp_parse_uri: error parsing uri 237.123.43.3:6120: no protocol
0:00:00.023144000 201831      0x1ee4d90 WARN                  udpsrc gstudpsrc.c:607:gst_udpsrc_set_uri:<udpsrc0> error: error parsing uri 237.123.43.3:6120
0:00:00.023197705 201831      0x1ee4d90 INFO              gstreamill source.c:400:element_create: Create element udpsrc success.
0:00:00.023747266 201831      0x1ee4d90 INFO              gstreamill source.c:400:element_create: Create element queue success.
0:00:00.024872533 201831      0x1ee4d90 INFO              gstreamill source.c:395:element_create: Set property: name=demuxer
0:00:00.024896191 201831      0x1ee4d90 INFO              gstreamill source.c:400:element_create: Create element tsdemux success.
0:00:00.025187278 201831      0x1ee4d90 INFO              gstreamill source.c:400:element_create: Create element queue success.
0:00:00.025797740 201831      0x1ee4d90 INFO              gstreamill source.c:400:element_create: Create element h264parse success.
0:00:00.026134594 201831      0x1ee4d90 INFO              gstreamill source.c:400:element_create: Create element queue success.
0:00:00.034056623 201831      0x1ee4d90 INFO              gstreamill source.c:400:element_create: Create element avdec_h264 success.
0:00:00.034380140 201831      0x1ee4d90 INFO              gstreamill source.c:400:element_create: Create element queue success.
0:00:00.035093453 201831      0x1ee4d90 INFO              gstreamill source.c:395:element_create: Set property: name=video
0:00:00.035120533 201831      0x1ee4d90 INFO              gstreamill source.c:400:element_create: Create element appsink success.
0:00:00.035464510 201831      0x1ee4d90 INFO              gstreamill source.c:400:element_create: Create element queue success.
0:00:00.035976082 201831      0x1ee4d90 INFO              gstreamill source.c:400:element_create: Create element ac3parse success.
0:00:00.036258422 201831      0x1ee4d90 INFO              gstreamill source.c:400:element_create: Create element queue success.
0:00:00.036884975 201831      0x1ee4d90 INFO              gstreamill source.c:400:element_create: Create element avdec_ac3 success.
0:00:00.037160895 201831      0x1ee4d90 INFO              gstreamill source.c:400:element_create: Create element queue success.
0:00:00.037631218 201831      0x1ee4d90 INFO              gstreamill source.c:395:element_create: Set property: name=audio
0:00:00.037662017 201831      0x1ee4d90 INFO              gstreamill source.c:400:element_create: Create element appsink success.
0:00:00.038471076 201831      0x1ee4d90 INFO              gstreamill encoder.c:589:encoder_extract_streams: encoder stream audio found appsrc name=audio ! queue ! audioconvert ! queue ! voaacenc name=voaacenc0 ! queue ! aacparse ! queue ! muxer.
0:00:00.038500302 201831      0x1ee4d90 INFO              gstreamill encoder.c:589:encoder_extract_streams: encoder stream video found appsrc name=video ! queue ! x264enc ! queue ! muxer.
0:00:00.039156171 201831      0x1ee4d90 INFO              gstreamill source.c:395:element_create: Set property: name=audio
0:00:00.039176830 201831      0x1ee4d90 INFO              gstreamill source.c:400:element_create: Create element appsrc success.
0:00:00.039357366 201831      0x1ee4d90 INFO              gstreamill source.c:400:element_create: Create element queue success.
0:00:00.039869011 201831      0x1ee4d90 INFO              gstreamill source.c:400:element_create: Create element audioconvert success.
0:00:00.040156605 201831      0x1ee4d90 INFO              gstreamill source.c:400:element_create: Create element queue success.
0:00:00.040884622 201831      0x1ee4d90 INFO              gstreamill source.c:395:element_create: Set property: name=voaacenc0
0:00:00.040907614 201831      0x1ee4d90 INFO              gstreamill source.c:400:element_create: Create element voaacenc success.
0:00:00.041183715 201831      0x1ee4d90 INFO              gstreamill source.c:400:element_create: Create element queue success.
0:00:00.041483354 201831      0x1ee4d90 INFO              gstreamill source.c:400:element_create: Create element aacparse success.
0:00:00.041777593 201831      0x1ee4d90 INFO              gstreamill source.c:400:element_create: Create element queue success.
0:00:00.042368212 201831      0x1ee4d90 INFO              gstreamill source.c:395:element_create: Set property: name=video
0:00:00.042388639 201831      0x1ee4d90 INFO              gstreamill source.c:400:element_create: Create element appsrc success.
0:00:00.042563101 201831      0x1ee4d90 INFO              gstreamill source.c:400:element_create: Create element queue success.
0:00:00.044190078 201831      0x1ee4d90 INFO              gstreamill source.c:400:element_create: Create element x264enc success.
0:00:00.044528550 201831      0x1ee4d90 INFO              gstreamill source.c:400:element_create: Create element queue success.
0:00:00.045209059 201831      0x1ee4d90 INFO              gstreamill source.c:395:element_create: Set property: name=muxer
0:00:00.045232031 201831      0x1ee4d90 INFO              gstreamill source.c:400:element_create: Create element mpegtsmux success.
0:00:00.045408249 201831      0x1ee4d90 INFO              gstreamill source.c:400:element_create: Create element queue success.
0:00:00.045766556 201831      0x1ee4d90 INFO              gstreamill source.c:400:element_create: Create element appsink success.
0:00:00.045884626 201831      0x1ee4d90 INFO              gstreamill encoder.c:640:complete_request_element: Request element link: queue -> muxer
0:00:00.045903269 201831      0x1ee4d90 INFO              gstreamill encoder.c:640:complete_request_element: Request element link: queue -> muxer
0:00:00.046058629 201831      0x1ee4d90 INFO              gstreamill encoder.c:525:create_encoder_pipeline: Encoder appsrc found.
0:00:00.046078689 201831      0x1ee4d90 INFO              gstreamill encoder.c:547:create_encoder_pipeline: link element: appsrc name=audio -> queue
0:00:00.046141680 201831      0x1ee4d90 INFO              gstreamill encoder.c:547:create_encoder_pipeline: link element: queue -> audioconvert
0:00:00.046285563 201831      0x1ee4d90 INFO              gstreamill encoder.c:547:create_encoder_pipeline: link element: audioconvert -> queue
0:00:00.046414629 201831      0x1ee4d90 INFO              gstreamill encoder.c:547:create_encoder_pipeline: link element: queue -> voaacenc name=voaacenc0
0:00:00.046570602 201831      0x1ee4d90 INFO              gstreamill encoder.c:547:create_encoder_pipeline: link element: voaacenc name=voaacenc0 -> queue
0:00:00.046611408 201831      0x1ee4d90 INFO              gstreamill encoder.c:547:create_encoder_pipeline: link element: queue -> aacparse
0:00:00.046665231 201831      0x1ee4d90 INFO              gstreamill encoder.c:547:create_encoder_pipeline: link element: aacparse -> queue
0:00:00.046703975 201831      0x1ee4d90 INFO              gstreamill encoder.c:547:create_encoder_pipeline: link element: queue -> muxer
0:00:00.046780243 201831      0x1ee4d90 INFO              gstreamill encoder.c:525:create_encoder_pipeline: Encoder appsrc found.
0:00:00.046796597 201831      0x1ee4d90 INFO              gstreamill encoder.c:547:create_encoder_pipeline: link element: appsrc name=video -> queue
0:00:00.046833439 201831      0x1ee4d90 INFO              gstreamill encoder.c:547:create_encoder_pipeline: link element: queue -> x264enc
0:00:00.046892631 201831      0x1ee4d90 INFO              gstreamill encoder.c:547:create_encoder_pipeline: link element: x264enc -> queue
0:00:00.046931639 201831      0x1ee4d90 INFO              gstreamill encoder.c:547:create_encoder_pipeline: link element: queue -> muxer
0:00:00.046997925 201831      0x1ee4d90 INFO              gstreamill encoder.c:538:create_encoder_pipeline: Encoder appsink found.
0:00:00.047016805 201831      0x1ee4d90 INFO              gstreamill encoder.c:547:create_encoder_pipeline: link element: mpegtsmux name=muxer -> queue
0:00:00.047053640 201831      0x1ee4d90 INFO              gstreamill encoder.c:547:create_encoder_pipeline: link element: queue -> appsink
0:00:00.047903460 201831      0x1ee4d90 INFO              gstreamill job.c:737:job_start: Set source pipeline to play state ok
0:00:00.049937921 201831      0x1ee4d90 INFO              gstreamill job.c:760:job_start: Set encoder encoder.0 to play state ok
0:00:00.049967354 201831      0x1ee4d90 INFO              gstreamill job.c:763:job_start: Set job bgctv1 to play state ok
0:00:00.049984123 201831      0x1ee4d90 INFO              gstreamill main.c:534:main: start job result: success.

**Comment by zhangping** [comment]
现在显示如下信息，并且返回启动失败
```
Jan 11 10:02:16.417610 ERROR  default gstudpnetutils.c:92: error parsing uri 238.123.43.3:8008: no protocol
Jan 11 10:02:16.417677 WARN   udpsrc gstudpsrc.c:708: error: error parsing uri 238.123.43.3:8008
Jan 11 10:02:21.421545 WARN   gstreamill job.c:751: Set cctv0 source pipeline to play timeout.
Jan 11 10:02:21.421617 ERROR  gstreamill main.c:436: start livejob failure, exit
```
