### ISSUE TITLE
离线转码过程中没法判断转码是否完成

### ISSUE THREAD

**Issue by g522342435** [i4tv/gstreamill#61]
能否提供http接口查询离线转码是否完成

**Comment by zhangping** [comment]
如下思路：查询job状态的请求为POST，其中body是job本身，首先根据job的name查找是否为当前正在运行的job，如果是则进一步确定是想要查询的job本身，这是根据job的body来确定的，如果确认为是，怎返回当前状态。如果不是，则返回错误信息。根据job的name查找并非为当前运行的job，那么如果是非live的，则查找对应的输出，通过对应的输出来确认是转码完成还是转码出错。
