### ISSUE TITLE
heartbeat error in encoder part of gstreamill .. !!

### ISSUE THREAD

**Issue by Josuercuevas** [i4tv/gstreamill#62]
I have the following job for GSTREAMILL:

> ![job](https://cloud.githubusercontent.com/assets/7018934/7997717/4ce5cbb0-0b64-11e5-908e-93479e71e159.png)

OR in plain text is here:
{
    "name" : "test",
    "debug" : "gstreamill:7,wavenc:7",
    "log-path" : "FULL_PATH_TO_LOG/gstreamill_debug/log/",
    "source" : {
        "elements" : {
            "audioconvert" : {
                "caps" : "audio/x-raw,format=F32LE,channels=1,rate=44100"
            }
        },
        "bins" : [
            "alsasrc ! queue ! audioconvert ! queue ! appsink name=audio"
        ]
    },
    "encoders" : [
        {
            "elements": {
                "appsrc" : {
                    "property" : {
                        "format" : 3,
                        "is-live" : true
                    }
                },
		"filesink":{
			"property" : {
				"location" : "FULL_PATH_TO_LOG/output.wav"
			}
		}
            },
            "bins" : [
                "appsrc name=audio ! queue ! wavenc ! queue ! filesink"
            ]
        }
    ]
}

This and/or similar jobs will result in "Jun 04 19:38:07.441628 WARN   gstreamill gstreamill.c:390: test.encoder.0 job->output heart beat error". I am wondering who or what is in charge of updating the value of the pointer "job->output->encoders[j].heartbeat" inside the function "encoders_check()" which is location in file "gstreamill.c".

Since from the debug information, if I accumulate 2 seconds buffer and then later encode it with wavenc to later sink to a wav file, I get this results:

Jun 04 19:37:59.432412 WARN   gstreamill gstreamill.c:390: test.encoder.0 job->output heart beat error 31271437038, restart
Jun 04 19:38:01.434614 WARN   gstreamill gstreamill.c:390: test.encoder.0 job->output heart beat error 33273660942, restart
Jun 04 19:38:01.711252 WARN   gstreamill gstreamill.c:1574: uri /stat/gstreamill/job/crydetector not found.
Jun 04 19:38:03.436952 WARN   gstreamill gstreamill.c:390: test.encoder.0 job->output heart beat error 35275985345, restart
Jun 04 19:38:05.439261 WARN   gstreamill gstreamill.c:390: test.encoder.0 job->output heart beat error 37278293764, restart
Jun 04 19:38:06.715402 WARN   gstreamill gstreamill.c:1574: uri /stat/gstreamill/job/crydetector not found.
Jun 04 19:38:07.441628 WARN   gstreamill gstreamill.c:390: test.encoder.0 job->output heart beat error 39280649516, restart
Jun 04 19:38:09.442988 WARN   gstreamill gstreamill.c:390: test.encoder.0 job->output heart beat error 41282023415, restart
Jun 04 19:38:11.445268 WARN   gstreamill gstreamill.c:390: test.encoder.0 job->output heart beat error 43284299679, restart
Jun 04 19:38:11.712262 WARN   gstreamill gstreamill.c:1574: uri /stat/gstreamill/job/crydetector not found.
Jun 04 19:38:13.446645 WARN   gstreamill gstreamill.c:390: test.encoder.0 job->output heart beat error 45285676823, restart
Jun 04 19:38:15.448959 WARN   gstreamill gstreamill.c:390: test.encoder.0 job->output heart beat error 47287991978, restart
Jun 04 19:38:16.712785 WARN   gstreamill gstreamill.c:1574: uri /stat/gstreamill/job/crydetector not found.
Jun 04 19:38:17.451091 WARN   gstreamill gstreamill.c:390: test.encoder.0 job->output heart beat error 49290121775, restart
Jun 04 19:38:19.453395 WARN   gstreamill gstreamill.c:390: test.encoder.0 job->output heart beat error 51292428595, restart
Jun 04 19:38:21.455086 WARN   gstreamill gstreamill.c:390: test.encoder.0 job->output heart beat error 53294117424, restart

The above simply means, that the encoder heartbeat value "job->output->encoders[j].heartbeat" is never updated, so when doing the following:

now = gst_clock_get_time (gstreamill->system_clock);
time_diff = GST_CLOCK_DIFF (*(job->output->encoders[j].heartbeat), now);
if ((time_diff > ENCODER_OUTPUT_HEARTBEAT_THRESHHOLD) && gstreamill->daemon) {
             ///RESTART PART
}

It will always restart at 30 seconds which is the "ENCODER_OUTPUT_HEARTBEAT_THRESHHOLD" value by default. And of course then the job is restarted it will take 30 seconds to see this behaviour again, but if the restart part is deactivated I will see that the "heart beat error" is because the variable "job->output->encoders[j].heartbeat" never changes values since the last moment we launched the job.

I was wondering if this is normal? or if is not, why the heart beat value in the encoder is never updated?

Thank you for your help!!

Josue

**Comment by zhangping** [comment]
gstreamill check encoder appsink output， you output to filesink directly without appsink, so it restart every 30s.

**Comment by Josuercuevas** [comment]
Got it !, so on both pipelines (source and encoders) we have to put appsink at the end of the bin? otherwise heart beat is not updated. I'll try it out and post my findings thanks!!

**Comment by Josuercuevas** [comment]
I have been testing it but there still a small issue that I think is very interesting, if you are using a sink element like "filesink" for example:

"bins" : [
"appsrc name=audio ! queue ! wavenc ! queue ! filesink"
]

How come you can use appsink? because I tried:

"bins" : [
"appsrc name=audio ! queue ! wavenc ! queue ! filesink ! queue ! appsink"
]

And I still have the same problem, my guess is because no samples will ever get to appsink.
and if you put it before:

"bins" : [
"appsrc name=audio ! queue ! wavenc ! queue ! appsink ! queue ! filesink"
]

Now I have heart beat error on the stream and the encoder?, is that normal?

Thanks for your help

Josue

**Comment by zhangping** [comment]
only one xxxsink allow:

"appsrc name=audio ! queue ! wavenc ! queue ! appsink

or

"appsrc name=audio ! queue ! wavenc ! queue ! filesink

gstreamill can check appsink and can't check filesink.

gstreamill should don't check filesink, I will accomplish it.
