### ISSUE TITLE
 gstreamill -j examples/test.job   error

### ISSUE THREAD

**Issue by yikai2651** [i4tv/gstreamill#66]
gstreamill -j examples/test.job
0:00:00.008838005 22521      0x26e1810 ERROR             gstreamill httpserver.c:606:socket_prepare: Bind socket 6 error: Address already in use
0:00:00.009008569 22521      0x26e1810 ERROR             gstreamill httpstreaming.c:747:httpstreaming_start: Start streaming httpserver error!
0:00:00.009385555 22521      0x26e1810 ERROR             gstreamill main.c:500:main: start httpstreaming error, exit.
0:00:00.009663763 22521      0x26e1810 ERROR             gstreamill main.c:221:remove_pid_file: unlink pid file error: No such file or directory

**Comment by zhangping** [comment]
Maybe you have already started a gstreamill, it have bind the port.

**Comment by Josuercuevas** [comment]
Yes, that is the issue I believe gstreamill is already running, just check the processes in the background or services. If you installed gstreamill and you have reboot your machine probably gstreamill is running in the background.
