### ISSUE TITLE
gstreamill后台运行意外终止

### ISSUE THREAD

**Issue by hiccupzhu** [i4tv/gstreamill#68]
gdb追踪调试结果如下：
···
   +--encoder.c------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
   |244     static void copy_buffer (Encoder *encoder, GstBuffer *buffer)                                                                                                                          |
   |245     {                                                                                                                                                                                      |
   |246             gint size;                                                                                                                                                                     |
   |247             GstMapInfo info;                                                                                                                                                               |
   |248                                                                                                                                                                                            |
   |249             gst_buffer_map (buffer, &info, GST_MAP_READ);                                                                                                                                  |
   |250             if (*(encoder->output->tail_addr) + gst_buffer_get_size (buffer) < encoder->output->cache_size) {                                                                              |
   |251                     memcpy (encoder->output->cache_addr + *(encoder->output->tail_addr), info.data, gst_buffer_get_size (buffer));                                                         |
   |252                     *(encoder->output->tail_addr) = *(encoder->output->tail_addr) + gst_buffer_get_size (buffer);                                                                          |
   |253                                                                                                                                                                                            |
   |254             } else {                                                                                                                                                                       |
   |255                     size = encoder->output->cache_size - *(encoder->output->tail_addr);                                                                                                    |
  >|256                     memcpy (encoder->output->cache_addr + *(encoder->output->tail_addr), info.data, size);                                                                                 |
   |257                     memcpy (encoder->output->cache_addr, info.data + size, gst_buffer_get_size (buffer) - size);                                                                           |
   |258                     *(encoder->output->tail_addr) = gst_buffer_get_size (buffer) - size;                                                                                                   |
   |259             }                                                                                                                                                                              |
   |260             gst_buffer_unmap (buffer, &info);                                                                                                                                              |
   |261     }                                                                                                                                                                                      |
   |262                                                                                                                                                                                            |
   |263     static void udp_streaming (Encoder *encoder, GstBuffer *buffer)                                                                                                                        |
   |264     {                                                                                                                                                                                      |
   |265             gsize buffer_size;                                                                                                                                                             |
   |266             gssize offset;                                                                                                                                                                 |
   |267             GstFlowReturn ret;                                                                                                                                                             |
   |268                                                                                                                                                                                            |
   |269             offset = 0;                                                                                                                                                                    |
   |270             buffer_size = gst_buffer_get_size (buffer);                                                                                                                                    |
   +-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
multi-thre Thread 0x7fb75 In: new_sample_callback                                                                                                                           Line: 256  PC: 0x413e64 
warning: Invalid layout specified.
Usage: layout prev | next | <layout_name>

(gdb) up
#1  0x0000000000413e64 in memcpy (__len=63896, __src=<optimized out>, __dest=<optimized out>) at /usr/include/x86_64-linux-gnu/bits/string3.h:51
#2  copy_buffer (buffer=0x7fb7300048a0, encoder=0x1b5e050) at encoder.c:256
···

**Comment by zhangping** [comment]
编码输出64位对齐试试：
```
diff --git a/src/job.c b/src/job.c
index 213464d..1248e3c 100644
--- a/src/job.c
+++ b/src/job.c
@@ -268,6 +268,7 @@ static gsize status_output_size (gchar *job)
                 /* output share memory */
                 size += SHM_SIZE;
         }
+        size = (size / 8 + 1) * 8; /* 64bit alignment */

         return size;
 }
```

**Comment by hiccupzhu** [comment]
代码中使用了设备/dev/shm由于其默认大小为64MB，<=程序所需；故解决方案为加大/dev/shm的大小
# vi /etc/fstab
tmpfs                   /dev/shm                tmpfs   defaults,size=1024M        0 0

mount -o remount /dev/shm
