### ISSUE TITLE
时移ts片片长与下载的文件大小不一致

### ISSUE THREAD

**Issue by 13426136199** [i4tv/gstreamill#79]
160.105服务器上一段时间内出现ts片长与下载文件大小不一致现象；出现此现象后会重新建一个新文件夹（与正常录制不同，正常录制以一小时为时间点，每小时新建一个文件夹，此问题频繁新建文件夹）
如：频道XINDONGMAN，录制目录如下图

![1](https://cloud.githubusercontent.com/assets/15663015/12283448/3e8e4ed0-b9e1-11e5-921f-8fed191cf2ca.png)
具体文件夹内ts情况如图：
![2](https://cloud.githubusercontent.com/assets/15663015/12283453/5241abde-b9e1-11e5-9e36-0fbf812a355a.png)
对应log信息如下:
![3](https://cloud.githubusercontent.com/assets/15663015/12283462/6036d1ec-b9e1-11e5-8cc4-7e9df3a3b496.png)

**Comment by zhangping** [comment]
这个是纯切片的，由于组播源时间戳错误造成的，目前还没有找到比较理想的解决方案。

**Comment by zhangping** [comment]
这个问题还会造成录制内容不能及时删除，结果造成磁盘满，进而gstreamill不能正常运行。

**Comment by zhangping** [comment]
不在采用pts来计算分片时长，采用按帧计算的方法，参考：

规范的7.4.1.2.4，用于找到一帧的开头
