### ISSUE TITLE
web管理页面媒体上载无反应

### ISSUE THREAD

**Issue by shakin** [i4tv/gstreamill#84]
gstreamill编译安装完成后(按照文档已安装所需依赖),
执行gstreamill,在管理端点击"媒体上传"无反应呢 ,请问是漏掉了什么设置还是需要安装其他撒呢 ?

或许这不是程序上的问题,只是文档遗漏?

**Comment by zhangping** [comment]
转码和界面有段时间没有维护了，应该是有问题，我抽时间看看。

**Comment by zhangping** [comment]
我试了一下，是可有上载的，你能打开浏览器的开发者工具看一下具体情况吗？

**Comment by shakin** [comment]
好的，我回去后看看，环境是装在家里的一台ubuntu 14.04上的．装好gstreamill后，用firefox,chrome两个浏览器都试过了　，管理端页面可以进，但是就是上传那个按钮点击后无效．

回去F12看看是不是javascript之类的无效了．
