### ISSUE TITLE
compile error on ubuntu 14,04 lts

### ISSUE THREAD

**Issue by drghetia** [i4tv/gstreamill#95]
hello sir,

i follow instruction but i am getting this error while i compile gstreamill on ubuntu 14.04 lts 64 bit.

here is my log,

[gstreamill compile error.txt](https://github.com/i4tv/gstreamill/files/816491/gstreamill.compile.error.txt)

**Comment by zhangping** [comment]
Please compile it on ubuntu 16.04.2. 

If compile gstreamill on ubuntu 14.04.5, install gstreamer from source instead install gstreamer dev packages.
